spring.application.name=comiverse
server.port=8081
spring.main.allow-bean-definition-overriding=true

# Database Configuration
# Cloud DB (Railway) - Uncomment to use:
 spring.datasource.url=jdbc:postgresql://reseau.proxy.rlwy.net:28965/railway
 spring.datasource.username=postgres
 spring.datasource.password=uvFlNJkQxJdeBJNWHJLkTwGZYMfkGJWI

# Local DB (Environment Variables) - Active:
#spring.datasource.url=jdbc:postgresql://localhost:5432/comiverse
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

server.servlet.context-path=/api

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

logging.level.root=INFO
logging.level.com.sep.comiverse=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT Configuration
app.auth.tokenSecret=${JWT_SECRET}
app.auth.tokenExpirationMs=86400000

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
app.oauth2.authorizedRedirectUri=${AUTHORIZED_REDIRECT_URI:http://localhost:5173/oauth2/redirect}

# Email Configuration
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

#Cloudinary Configuration
cloudinary.cloud-name=${CLOUD_USERNAME:mock-cloud-name}
cloudinary.api-key=${CLOUD_KEY:mock-api-key}
cloudinary.api-secret=${CLOUD_SECRET:mock-api-secret}

